Some ubuntu fixes

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -100,11 +100,11 @@ function ubuntu_setup() {
     _cmd "sudo apt-get install python3-argcomplete"
 
     if command -v activate-global-python-argcomplete3 &>/dev/null; then
-        _cmd "sudo activate-global-python-argcomplete3"
+      _cmd "sudo activate-global-python-argcomplete3"
     elif command -v activate-global-python-argcomplete &>/dev/null; then
-        _cmd "sudo activate-global-python-argcomplete"
+      _cmd "sudo activate-global-python-argcomplete"
     else
-        _cmd "echo 'unable to find activate-global-python-argcomplete' && exit 1"
+      _cmd "echo 'unable to find activate-global-python-argcomplete' && exit 1"
     fi
   fi
   if ! dpkg -s python3 >/dev/null 2>&1; then
